name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Linter
        run: dart analyze --fatal-infos
      - name: Check format
        run: dart format -o none --set-exit-if-changed .

      # TODO: enable later (easily takes 3 min)
      # - name: Build APK
      #   run: flutter build apk
