name: CI

on:
  workflow_call: {}
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: "${{ github.workflow }} - ${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

# Flutter GHA: https://github.com/marketplace/actions/flutter-action
jobs:
  check_builds:
    strategy:
      matrix:
        build:
          - appbundle
          - apk
          - linux
          - web

    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v5
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
          pub-cache-key: "flutter-pub:os:-:channel:-:version:-:arch:-:hash:"
          pub-cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"

      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - if: ${{ matrix.build == 'linux' }}
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - name: Build ${{ matrix.build }}
        run: flutter build ${{ matrix.build }}

  check_format:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v5
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Linter
        run: dart analyze --fatal-infos
      - name: Check format
        run: dart format -o none --set-exit-if-changed .      

  checks:
    needs:
      - check_builds
      - check_format
    
    runs-on: ubuntu-latest
    steps:
      - run: echo OK